version: '3'

services:
  api:
    image: node:12
    command: sh -c "yarn && yarn typeorm migration:run && yarn dev:server"
    ports:
      - 3333:3333
    working_dir: /api
    volumes:
      - .:/api
    env_file:
      - .env.api
    stdin_open: true
    tty: true
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbpostgres:/var/lib/postgresql/data
    env_file:
      - .env.database

volumes:
  dbpostgres:
