version: '3'

services:
  api:
    image: node:12
    command: sh -c "yarn && yarn typeorm migration:run && yarn dev:server"
    ports:
      - 3333:3333
    working_dir: /api
    volumes:
      - .:/api
    environment:
      - PORT=3333
      - HOST_DB=postgres
      - PORT_DB=5432
      - NAME_DB=gostack_gobarber
      - PASSWORD_DB=docker
      - USERNAME_DB=postgres
    stdin_open: true
    tty: true
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gostack_gobarber
      - POSTGRES_PASSWORD=docker
    volumes:
      - dbpostgres:/var/lib/postgresql/data

volumes:
  dbpostgres:
